# Even Fibonacci numbers.
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.


def fibonacci_sum(max_value):
    current_number = 1
    previous_number = current_number
    even_valued_sum = 0

    while (True):
        next_number = current_number + previous_number
        previous_number = current_number
        if(next_number > max_value):
            return even_valued_sum

        if(next_number % 2 == 0):
            even_valued_sum += next_number

        current_number = next_number


sum = fibonacci_sum(4000000)
print(sum)